name: Deploy to Amazon EKS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR
      run: |
         aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 948425238459.dkr.ecr.us-east-1.amazonaws.com
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: us-east-1

    - name: Build and push Docker image
      run: |
        docker build -t simple-node-app .
        docker tag simple-node-app:latest 948425238459.dkr.ecr.us-east-1.amazonaws.com/simple-node-app:latest
        docker push 948425238459.dkr.ecr.us-east-1.amazonaws.com/simple-node-app:latest

    - name: Update kubeconfig
      run: |
          aws eks update-kubeconfig --name my-eks-cluster --region us-east-1
      env:
         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
         AWS_REGION: us-east-1


    - name: Deploy to EKS
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml

